server:
  port: 7777

spring:
  application:
    name: @artifactId@
  profiles:
    active: dev  # 当前激活配置，默认dev
  datasource:
    dynamic:
      strict: true # 使用严格模式处理

mybatis-plus:
  mapper-locations:
    - classpath:/mapper/*Mapper.xml
    - src/main/java/com/qinweizhao/generator/database/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      logic-delete-value: "NOW()" # 逻辑已删除值(使用当前时间标识)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


## 生产环境时不应在配置文件中配置
jasypt:
  encryptor:
    password: "123456"

